name: Renew Bot
on:
  workflow_dispatch:      # 允许手动触发
  schedule:
    # 每天北京时间早上 9 点和晚上 9 点各自动执行一次
    - cron: '0 */6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with: {python-version: '3.10'}
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          # 注意这里将 libasound2 修改为了 libasound2t64
          sudo apt-get install -y xvfb libx11-6 libxkbfile1 libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2t64
          pip install -r requirements.txt
          playwright install chromium
          
      - name: Setup Gost Proxy
        run: |
          # 👇👇👇 正在启动gost代理 👇👇👇                
          wget -q https://github.com/ginuerzh/gost/releases/download/v2.11.5/gost-linux-amd64-2.11.5.gz
          gunzip -f gost-linux-amd64-2.11.5.gz
          chmod +x gost-linux-amd64-2.11.5
          
          echo "🔗 启动 Gost 隧道: $SOCKS5_URL"
          ./gost-linux-amd64-2.11.5 -L=http://:1080 -F="${{ secrets.SOCKS5_URL }}" > gost.log 2>&1 &
          
          sleep 5
          echo "--- 🌐 连通性测试 ---"
          curl -I -x http://127.0.0.1:1080 https://www.google.com
          
      - name: Run script
        env:
          NOPECHA_API_KEY: ${{ secrets.NOPECHA_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PROXY: 127.0.0.1:1080
         # http_proxy: socks5://127.0.0.1:10808
         # https_proxy: socks5://127.0.0.1:10808
        # 使用 xvfb-run 启动，它会创建一个虚拟的显示环境，彻底解决 Missing X server 问题
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" python -u main.py
      #  run:  all_proxy=socks5://127.0.0.1:10808 xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" python -u main.py
